services:
  # ==========================================================================
  # POSTGRESQL - DEDICADO A apirestequipment
  # ==========================================================================
  postgres:
    image: postgres:17-alpine
    container_name: ${POSTGRES_CONTAINER}
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - equip-network

  # ==========================================================================
  # MINIO - S3-compatible object storage
  # ==========================================================================
  # minio:
  #   image: minio/minio:RELEASE.2024-12-18T13-15-44Z
  #   container_name: ${MINIO_CONTAINER}
  #   restart: always
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   ports:
  #     - "127.0.0.1:9200:9000"   # S3 API
  #     - "127.0.0.1:9201:9001"   # Web console
  #   volumes:
  #     - minio_data:/data
  #   command: server --console-address ":9001" /data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - equip-network

  # ==========================================================================
  # PGADMIN - PostgreSQL admin UI (solo dev)
  # ==========================================================================
  pgadmin:
    image: elestio/pgadmin:REL-9_8
    container_name: equip-pga
    # restart: always
    ports:
      - '127.0.0.1:8091:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - equip-network

volumes:
  postgres_data:
  minio_data:

networks:
  equip-network:
    driver: bridge
